databases:
  - name: cen3031projectdb
    plan: free
    databaseName: cen3031project
    user: cen3031projectuser

services:
  - type: web
    plan: free
    name: cen3031project
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn CEN3031Project.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cen3031projectdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4